### ISSUE TITLE
Too much break lines

### ISSUE THREAD

**Issue by Cretezy** [samclarke/SBBCodeParser#2]
Hey!
Ok, so my bbcode is:
"
Hey
Hello
Moo
"

But it outputs as
"
Hey
< br >
< br >
Hello
< br >
< br >
Moo
< br >
< br >
"

How can I remove that second < br > ?

(Added a space in br because Github was parsing it)

**Comment by LiamDawe** [comment]
I can confirm this is an issue, way way too many new lines are processed.

**Comment by diegargon** [comment]
I comment line 697 on Documment.php and fix that. Not ask. :P

//$str      = preg_replace('/[\r\n|\r]/', "\n", $str);
